import bg from './bg.png'
import cloudyDay1 from './cloudy-day-1.svg'
import cloudyDay from './cloudy-day.svg'
import cloudy from './cloudy.svg'
import humidity from './humidity.svg'
import logo from './logo.svg'
import pressure from './pressure.svg'
import rainy1 from './rainy-1.svg'
import rainy4 from './rainy-4.svg'
import rainy6 from './rainy-6.svg'
import snowy1 from './snowy-1.svg'
import snowy2 from './snowy-2.svg'
import snowy4 from './snowy-4.svg'
import snowy5 from './snowy-5.svg'
import sun from './sun.svg'
import temp from './temp.svg'
import thunder from './thunder.svg'
import wind from './wind.svg'

export {humidity,pressure,temp,wind}